[package]
name = "sqltk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqltk_core = { path = "../toolkit_core" }
sqltk_derive = { path = "../derive" }
bigdecimal = { workspace = true }
derive_more = "0.99.17"
