[workspace]
resolver = "2"
members = ["packages/*"]

[workspace.package]
edition = "2021"

[workspace.dependencies]
sqlparser = { git = "https://github.com/cipherstash/sqlparser-rs", branch = "main", features = [
  "bigdecimal",
] }
bigdecimal = "0.4.6"