[workspace]
resolver = "2"
members = [
    "packages/*"
]

[workspace.dependencies]
sqlparser = { version = "0.43.1", features = ["bigdecimal"] }
bigdecimal = { version = "^0.4.2" }
aquamarine = "0.5.0"


[profile.dev]
incremental = true