[workspace]
resolver = "2"
members = [
    "crates/*"
]

[workspace.dependencies]
sqlparser = { version = "0.44.0", features = ["bigdecimal"] }
bigdecimal = { version = "^0.4.2" }

[profile.dev]
incremental = true
