[package]
name = "sqltk_meta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "2.0.37", features = ["full", "extra-traits", "printing"] }
proc-macro2 = { version = "1.0.67", features = ["span-locations"] }
quote = { version = "1" }
serde_derive = "1.0.193"
serde = { version = "1.0.193", features = ["serde_derive"] }
