[package]
name = "sqltk"
resolver = "2"
description = "Enhanced Visitor implementation for sqlparser"
version = "0.1.0"
publish = true
edition = "2021"
authors = ["James Sadler <james@cipherstash.com>", "Robin Howard <robin@cipherstash.com>"]
homepage = "https://github.com/cipherstash/sqltk"
documentation = "https://docs.rs/sqltk/"
keywords = ["sql", "lexer", "parser", "visitor", "transform", "analyze", "analyse", "cipherstash"]
repository = "https://github.com/cipherstash/sqltk"
license = "MIT"
readme = "README.md"
include = [
    "build.rs",
    "src/**/*.rs",
    "Cargo.toml",
    "../../CONTRIBUTING.md",
    "../../LICENSE",
    "../../README.md",
]

[dependencies]
sqlparser = { workspace = true }
bigdecimal = { workspace = true }

[build-dependencies]
sqltk-codegen = { path = "../sqltk-codegen", version = "0.1.0" }