[package]
name = "sqltk_derive"
resolver = "2"
description = "Produces AST node metadata from sqlparser types and provides macros to generate Visitor implementations"
version = "0.1.0"
edition = "2021"
authors = ["James Sadler <james@cipherstash.com>"]
homepage = "https://github.com/cipherstash/sqltk"
documentation = "https://docs.rs/sqltk/"
keywords = ["ansi", "sql", "lexer", "parser", "ast", "analyze", "cipherstash"]
repository = "https://github.com/cipherstash/sqltk"
license = "Apache-2.0"
include = [
    "src/**/*.rs",
    "Cargo.toml",
    "LICENSE.TXT",
]

[lib]
proc-macro = true

[dependencies]
sqltk_core = { path = "../toolkit_core" }
sqltk_codegen_helpers = { path = "../codegen_helpers" }
Inflector = "^0.11.4"
syn = { version = "2.0.37", features = ["full", "extra-traits"] }
proc-macro2 = { version = "1.0.67", features = ["span-locations"] }
proc-macro-crate = "3.0.0"
quote = { version = "1" }
sqltk_codegen = { path = "../codegen" }
sqltk_meta = { path = "../meta" }
serde_json = "1.0.108"
indoc = "2.0.4"

[package.metadata.release]
# Instruct `cargo release` to not run `cargo publish` locally:
# https://github.com/sunng87/cargo-release/blob/master/docs/reference.md#config-fields
# See docs/releasing.md for details.
publish = false

[build-dependencies]
sqltk_codegen = { path = "../codegen" }
sqltk_core = { path = "../toolkit_core" }
syn = { version = "2.0.37", features = ["full", "extra-traits", "visit-mut"] }
proc-macro2 = { version = "1.0.67", features = ["span-locations"] }
quote = { version = "1" }
sqlparser = { workspace = true }
