[package]
name = "sqltk_derive"
resolver = "2"
description = "Produces AST node metadata from sqlparser types and provides macros to generate Visitor implementations"
version = "0.1.0"
edition = "2021"
authors = ["James Sadler <james@cipherstash.com>"]
homepage = "https://github.com/cipherstash/sqlparser-ast-toolkit"
documentation = "https://docs.rs/sqlparser-ast-toolkit/"
keywords = ["ansi", "sql", "lexer", "parser", "ast", "analyze", "cipherstash"]
repository = "https://github.com/cipherstash/sqlparser-ast-toolkit"
license = "Apache-2.0"
include = [
    "src/**/*.rs",
    "Cargo.toml",
    "LICENSE.TXT",
]

[lib]
proc-macro = true

[features]
default = ["bigdecimal"]
bigdecimal = ["sqlparser/bigdecimal"]

[dependencies]
syn = { version = "2.0.37", features = ["full", "extra-traits"] }
proc-macro2 = { version = "1.0.67", features = ["span-locations"] }
proc-macro-error = { version = "1" }
proc-macro-crate = "3.0.0"
quote = { version = "1" }
prettyplease = "0.2.15"
cfg-expr = "0.15.5"
built = "0.7.0"
cargo_metadata = "0.18.0"
topological-sort = "0.2.2"
darling = "0.20.3"
static-include-bytes = "2.0.0"
sqltk_codegen = { path = "../codegen" }
serde_json = "1.0.108"
impls = "*"

[package.metadata.release]
# Instruct `cargo release` to not run `cargo publish` locally:
# https://github.com/sunng87/cargo-release/blob/master/docs/reference.md#config-fields
# See docs/releasing.md for details.
publish = false

[build-dependencies]
sqltk_codegen = { path = "../codegen" }
syn = { version = "2.0.37", features = ["full", "extra-traits", "visit-mut"] }
proc-macro2 = { version = "1.0.67", features = ["span-locations"] }
quote = { version = "1" }
prettyplease = "0.2.15"
cfg-expr = "0.15.5"
cargo_metadata = "0.18.0"
sqlparser = { version = "^0.39.0" }
